### ISSUE TITLE
Performance regression of `regex-automata` from 0.2 to 0.3.1

### ISSUE THREAD

**Issue by oxalica** [rust-lang/regex#1029]
#### What version of regex are you using?

`regex-automata` 0.3.1

#### Describe the bug at a high level.

I'm using `regex_automata::dfa::dense::Dfa<Vec<u32>>` [for tokenization](https://github.com/oxalica/nil/blob/a5422a2168de28b94e7f981651d0e2f4b6b7e0e4/crates/syntax/src/lexer.rs#L24). Upgrading it from 0.2 to 0.3.1 will cause >100% performance regression on large files.

#### What are the steps to reproduce the behavior?

I simplified the original code to a single DFA in a single file: [see this gist](https://gist.github.com/oxalica/c720be3fe00f4880e642cccc705f73bb).
The input file `BENCH_FILE` is from [`all-packages.nix` of NixOS/nixpkgs](https://raw.githubusercontent.com/NixOS/nixpkgs/f9e94676ce6c7531c44d38da61d2669ebec0f603/pkgs/top-level/all-packages.nix) which is about 1.3MiB.

Benchmark command: `BENCH_FILE=/path/to/all-packages.nix cargo run --release -- --bench`

#### What is the actual behavior?

The results from both versions are the same, while 0.3.1 costs +211% more run time without LTO, or +77% with LTO.

#### What is the expected behavior?

No significant performance regression.

**Comment by BurntSushi** [comment]
Without LTO, I was able to get it down to:

```
$ BENCH_FILE=all-packages.nix ./target/release/i1029 --bench lex_0_
Gnuplot not found, using plotters backend
lex_0_3                 time:   [5.1468 ms 5.1512 ms 5.1559 ms]
                        change: [-0.7741% -0.6408% -0.5166%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 4 outliers among 100 measurements (4.00%)
  3 (3.00%) high mild
  1 (1.00%) high severe

lex_0_2                 time:   [3.6026 ms 3.6069 ms 3.6114 ms]
                        change: [+0.2592% +0.4406% +0.6263%] (p = 0.00 < 0.05)
                        Change within noise threshold.
```

And then with LTO:

```
$ BENCH_FILE=all-packages.nix ./target/release/i1029 --bench lex_0_
Gnuplot not found, using plotters backend
lex_0_3                 time:   [5.1701 ms 5.1730 ms 5.1758 ms]
                        change: [+0.3135% +0.4220% +0.5280%] (p = 0.00 < 0.05)
                        Change within noise threshold.

lex_0_2                 time:   [3.2121 ms 3.2148 ms 3.2175 ms]
                        change: [-11.009% -10.873% -10.746%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high mild
```

The problem, without LTO, was that there were several functions not getting inline that really ought to be. I fixed that with `inline(always)` annotations. As expected, that make the without LTO and with LTO timings become much closer. But `regex-automata 0.2` is still faster.

The underlying issue here is that this is a latency benchmark, and I've generally prioritized throughput. I'm open to improving latency, but it's quite tricky to do. `regex-automata 0.2` was never intended for anyone to use, so I don't really consider it a reasonable baseline. It was in a half-finished state and I published it (with a giant warning) to unblock some folks that really wanted it published.

One of the things that changed between `0.2` and `0.3` was a lot of polishing with respect to the APIs around search configuration, such as how to compute start states, whether to run anchored searches and so on. This has likely had a sub-optimal impact on overall codegen from a latency perspective. It's not quite clear to me how to win that back. There's a penalty being paid here for the abstraction and configuration offered by the crate.

I will note that you do technically have an escape hatch here. You can write your own search routine because the lower level DFA routines are all exposed. It was a specific design goal that all of the routines used by a DFA `find_leftmost_fwd` search could be implemented in terms of public APIs without penalty. Which means you can write the specialized code you need. This is basically my justification for prioritizing throughput so much higher for latency, because while inconvenient and more difficult, you have options:

```rust
pub fn lex_0_3_manual(src: &[u8]) -> Vec<(u32, u32)> {
    use regex_automata::{dfa::Automaton, Anchored};

    let dfa = &*DFA03;
    let start =
        dfa.universal_start_state(Anchored::Yes).expect("no look-around");
    let search = |haystack: &[u8]| -> Option<(u32, usize)> {
        let mut sid = start;
        let mut mat = None;
        for (i, byte) in haystack.iter().copied().enumerate() {
            sid = dfa.next_state(sid, byte);
            if dfa.is_match_state(sid) {
                let pid = dfa.match_pattern(sid, 0);
                mat = Some((pid.as_u32(), i));
            } else if dfa.is_dead_state(sid) {
                return mat;
            }
        }
        sid = dfa.next_eoi_state(sid);
        if dfa.is_match_state(sid) {
            let pid = dfa.match_pattern(sid, 0);
            mat = Some((pid.as_u32(), haystack.len()));
        }
        mat
    };

    let mut out = Vec::new();
    let mut offset = 0;
    while offset < src.len() {
        let rest = &src[offset..];
        let Some((pid, match_offset)) = search(rest) else {
            offset += 1;
            continue;
        };
        out.push((pid, match_offset as u32));
        offset += match_offset;
    }
    out
}
```

And the results:

```
$ BENCH_FILE=all-packages.nix ./target/release/i1029 --bench
Gnuplot not found, using plotters backend
lex_0_3_manual          time:   [3.5157 ms 3.5174 ms 3.5192 ms]
                        change: [+0.0507% +0.1035% +0.1611%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 2 outliers among 100 measurements (2.00%)
  2 (2.00%) high severe

lex_0_3_api             time:   [5.1145 ms 5.1183 ms 5.1223 ms]
                        change: [-0.5894% -0.4813% -0.3867%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 3 outliers among 100 measurements (3.00%)
  1 (1.00%) low mild
  2 (2.00%) high mild

lex_0_2                 time:   [3.5836 ms 3.5923 ms 3.6010 ms]
                        change: [-0.9221% -0.6103% -0.2693%] (p = 0.00 < 0.05)
                        Change within noise threshold.
```

(I also get a small improvement if I use `Automaton::next_state_unchecked`, but it's small and might not be worth the use of `unsafe`. It depends on your risk tolerance.)

I put up #1030, which adds the `inline(always)` annotations to make the out-of-the-box perf better.

I'm open to folks trying to further optimize the out-of-the-box experience, but I generally consider "you can drop down and fix this yourself" to be good enough here.

**Comment by BurntSushi** [comment]
This is "fixed" in `regex-automata 0.3.2` on crates.io. (As in, `find_leftmost_fwd` is now about on par with LTO perf even when LTO is disabled.)

**Comment by oxalica** [comment]
Thanks for the fix and advice. Well, I still have some questions.

> The underlying issue here is that this is a latency benchmark, and I've generally prioritized throughput.

What's the difference between "throughput" and "latency" in case of regex matching? Does "throughput" mean the total time cost of searching all matched strings on a large haystack? My scenario is kinda like it I guess?

> There's a penalty being paid here for the abstraction and configuration offered by the crate. I will note that you do technically have an escape hatch here. You can write your own search routine because the lower level DFA routines are all exposed. It was a specific design goal that all of the routines used by a DFA find_leftmost_fwd search could be implemented in terms of public APIs without penalty.

So basically the extra cost comes from configuration APIs. But the bench code has only one configuration and a single entry call, the configuration checks should be eliminated by LLVM easily (via constant propagation). The fact that it fails surprised me a bit.

**Comment by BurntSushi** [comment]
> So basically the extra cost comes from configuration APIs.

That's my best guess. I may be wrong. Maybe some of the changes just resulted in a shift that led to sub-optimal shift that could be recovered by moving things around.

> The fact that it fails surprised me a bit.

Not me. LLVM isn't magic, but it is mostly a black box to me. It doesn't cut through layers arbitrarily.

> What's the difference between "throughput" and "latency" in case of regex matching? Does "throughput" mean the total time cost of searching all matched strings on a large haystack? My scenario is kinda like it I guess?

A latency benchmark is one in which the total runtime is dominated by constant factors. In this case, each individual search mostly reports matches of very small length. Therefore, the total time spent in the core search loop is relatively small compared to the costs needed to get to the search loop in the first place. That is, you're mostly measuring the costs required to start and stop a search.

Usually latency benchmarks are indicated by a high match frequency relative to the length of the haystack. This in turn does indeed mean that most searches on small haystacks are latency benchmarks. But not exclusively so, as in this case.

Popping up a level, my suspicion is that there might be a better way to wire up the task you're doing here. But it might require changing how you lex things. If I were doing this task, I might explore making the lexer match all portions of the haystack so that there is no "didn't match, so let's retry the search at the next offset." Then you might be able to just zip through the haystack without running distinct searches and just reporting matches as they're visited in the underlying DFA. But I ran out of energy to go down that path because I didn't want to start changing the task. And it's just a guess. It's not obvious to me it will be faster.

**Comment by oxalica** [comment]
> If I were doing this task, I might explore making the lexer match all portions of the haystack so that there is no "didn't match, so let's retry the search at the next offset." Then you might be able to just zip through the haystack without running distinct searches and just reporting matches as they're visited in the underlying DFA.

Oops, that's accidentally introduced by the benchmark simplification because some patterns are removed. My original code already matches on every current offset as long as the input is syntactically correct.

You can change `DQUOTE` and `QUOTE2` lines to following, then `try_search_fwd`/`find_leftmost_fwd` always returns `Some` on each starting point.
```
        DQUOTE = r#""[^"]*""#,
        QUOTE2 = "''([^']|'[^'])*''",
```

0.3.2 did make the without-LTO version performs almost as fast as LTO-ed version. Here I only benched LTO=fat version with 0.3.2:
```
lex_0_3                 time:   [7.2891 ms 7.2934 ms 7.2986 ms]
lex_0_3_manual          time:   [4.6289 ms 4.6309 ms 4.6332 ms]
lex_0_2                 time:   [4.2605 ms 4.2636 ms 4.2672 ms]
```
There seems to be only little difference if each search always return `Some` (7.6850ms before, with retry), and is still +78% slower than 0.2. The manual version does perform better and I'll use it for now.

**Comment by BurntSushi** [comment]
To be clear, my suggestion wasn't *just* to make a search always return `Some`. It was to do that *and find a way to traverse the automaton in one pass* without starting and stopping a new search for every token. _This might require more changes than just making the DFA match every part of the haystack._ It's just an idea.
